# Generated by Django 5.1.6 on 2025-02-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mobel', models.IntegerField(max_length=10)),
                ('account_no', models.IntegerField(max_length=14)),
                ('balance', models.FloatField(max_length=15)),
            ],
        ),
    ]
